export const fakeInfo = [
  {
    name: "John Smith",
    age: 25,
    email: "john.smith@example.com",
    address: "123 Main Street, Cityville",
    phone: "555-123-4567",
  },
  {
    name: "Emma Johnson",
    age: 32,
    email: "emma.johnson@example.com",
    address: "456 Oak Avenue, Townsville",
    phone: "555-987-6543",
  },
  {
    name: "Michael Brown",
    age: 40,
    email: "michael.brown@example.com",
    address: "789 Elm Road, Villageland",
    phone: "555-456-7890",
  },
  {
    name: "Olivia Davis",
    age: 28,
    email: "olivia.davis@example.com",
    address: "1010 Pine Court, Hamletown",
    phone: "555-789-1234",
  },
  {
    name: "William Johnson",
    age: 37,
    email: "william.johnson@example.com",
    address: "555 Cedar Lane, Suburbia",
    phone: "555-234-5678",
  },
  {
    name: "Sophia Williams",
    age: 22,
    email: "sophia.williams@example.com",
    address: "777 Maple Street, Urbanville",
    phone: "555-678-9012",
  },
  {
    name: "James Miller",
    age: 29,
    email: "james.miller@example.com",
    address: "888 Birch Avenue, Metropolis",
    phone: "555-345-6789",
  },
  {
    name: "Isabella Wilson",
    age: 31,
    email: "isabella.wilson@example.com",
    address: "999 Spruce Road, Megacity",
    phone: "555-567-8901",
  },
  {
    name: "Benjamin Anderson",
    age: 27,
    email: "benjamin.anderson@example.com",
    address: "111 Oak Avenue, Smalltown",
    phone: "555-789-0123",
  },
  {
    name: "Ava Martinez",
    age: 24,
    email: "ava.martinez@example.com",
    address: "222 Pine Street, Countyville",
    phone: "555-890-1234",
  },
  {
    name: "Alexander Taylor",
    age: 36,
    email: "alexander.taylor@example.com",
    address: "333 Elm Road, Boroughburg",
    phone: "555-901-2345",
  },
  {
    name: "Mia Anderson",
    age: 23,
    email: "mia.anderson@example.com",
    address: "444 Cedar Lane, Townberg",
    phone: "555-012-3456",
  },
  {
    name: "Ethan Lee",
    age: 26,
    email: "ethan.lee@example.com",
    address: "555 Maple Court, Villagetown",
    phone: "555-123-4567",
  },
  {
    name: "Amelia Moore",
    age: 35,
    email: "amelia.moore@example.com",
    address: "666 Birch Avenue, Hamletsville",
    phone: "555-234-5678",
  },
  {
    name: "Daniel Jackson",
    age: 30,
    email: "daniel.jackson@example.com",
    address: "777 Spruce Road, Suburbville",
    phone: "555-345-6789",
  },
  {
    name: "Ella Adams",
    age: 29,
    email: "ella.adams@example.com",
    address: "888 Oak Street, Urbanland",
    phone: "555-456-7890",
  },
  {
    name: "Matthew Wilson",
    age: 33,
    email: "matthew.wilson@example.com",
    address: "999 Pine Lane, Metrotown",
    phone: "555-567-8901",
  },
  {
    name: "Sofia Garcia",
    age: 27,
    email: "sofia.garcia@example.com",
    address: "111 Elm Avenue, Megatown",
    phone: "555-678-9012",
  },
  {
    name: "Jackson Hernandez",
    age: 25,
    email: "jackson.hernandez@example.com",
    address: "222 Cedar Road, Smallburg",
    phone: "555-789-0123",
  },
  {
    name: "Grace Rodriguez",
    age: 28,
    email: "grace.rodriguez@example.com",
    address: "333 Maple Court, Countytown",
    phone: "555-890-1234",
  },
  {
    name: "Henry King",
    age: 31,
    email: "henry.king@example.com",
    address: "444 Birch Street, Boroughville",
    phone: "555-901-2345",
  },
  {
    name: "Scarlett Anderson",
    age: 24,
    email: "scarlett.anderson@example.com",
    address: "555 Pine Road, Townland",
    phone: "555-012-3456",
  },
  {
    name: "Liam Martinez",
    age: 26,
    email: "liam.martinez@example.com",
    address: "666 Elm Avenue, Cityburg",
    phone: "555-123-4567",
  },
  {
    name: "Chloe Taylor",
    age: 33,
    email: "chloe.taylor@example.com",
    address: "777 Cedar Lane, Villaville",
    phone: "555-234-5678",
  },
  {
    name: "Emma Adams",
    age: 30,
    email: "emma.adams@example.com",
    address: "888 Maple Street, Hamletville",
    phone: "555-345-6789",
  },
  {
    name: "Oliver Jackson",
    age: 28,
    email: "oliver.jackson@example.com",
    address: "999 Elm Road, Suburbtown",
    phone: "555-456-7890",
  },
  {
    name: "Ava Garcia",
    age: 27,
    email: "ava.garcia@example.com",
    address: "111 Pine Avenue, Urbantown",
    phone: "555-567-8901",
  },
  {
    name: "John Smith",
    age: 25,
    email: "john.smith@example.com",
    address: "123 Main Street, Cityville",
    phone: "555-123-4567",
  },
  {
    name: "Emma Johnson",
    age: 32,
    email: "emma.johnson@example.com",
    address: "456 Oak Avenue, Townsville",
    phone: "555-987-6543",
  },
  {
    name: "Michael Brown",
    age: 40,
    email: "michael.brown@example.com",
    address: "789 Elm Road, Villageland",
    phone: "555-456-7890",
  },
  {
    name: "Olivia Davis",
    age: 28,
    email: "olivia.davis@example.com",
    address: "1010 Pine Court, Hamletown",
    phone: "555-789-1234",
  },
  {
    name: "William Johnson",
    age: 37,
    email: "william.johnson@example.com",
    address: "555 Cedar Lane, Suburbia",
    phone: "555-234-5678",
  },
  {
    name: "Sophia Williams",
    age: 22,
    email: "sophia.williams@example.com",
    address: "777 Maple Street, Urbanville",
    phone: "555-678-9012",
  },
  {
    name: "James Miller",
    age: 29,
    email: "james.miller@example.com",
    address: "888 Birch Avenue, Metropolis",
    phone: "555-345-6789",
  },
  {
    name: "Isabella Wilson",
    age: 31,
    email: "isabella.wilson@example.com",
    address: "999 Spruce Road, Megacity",
    phone: "555-567-8901",
  },
  {
    name: "Benjamin Anderson",
    age: 27,
    email: "benjamin.anderson@example.com",
    address: "111 Oak Avenue, Smalltown",
    phone: "555-789-0123",
  },
  {
    name: "Ava Martinez",
    age: 24,
    email: "ava.martinez@example.com",
    address: "222 Pine Street, Countyville",
    phone: "555-890-1234",
  },
  {
    name: "Alexander Taylor",
    age: 36,
    email: "alexander.taylor@example.com",
    address: "333 Elm Road, Boroughburg",
    phone: "555-901-2345",
  },
  {
    name: "Mia Anderson",
    age: 23,
    email: "mia.anderson@example.com",
    address: "444 Cedar Lane, Townberg",
    phone: "555-012-3456",
  },
  {
    name: "Ethan Lee",
    age: 26,
    email: "ethan.lee@example.com",
    address: "555 Maple Court, Villagetown",
    phone: "555-123-4567",
  },
  {
    name: "Amelia Moore",
    age: 35,
    email: "amelia.moore@example.com",
    address: "666 Birch Avenue, Hamletsville",
    phone: "555-234-5678",
  },
  {
    name: "Daniel Jackson",
    age: 30,
    email: "daniel.jackson@example.com",
    address: "777 Spruce Road, Suburbville",
    phone: "555-345-6789",
  },
  {
    name: "Ella Adams",
    age: 29,
    email: "ella.adams@example.com",
    address: "888 Oak Street, Urbanland",
    phone: "555-456-7890",
  },
  {
    name: "Matthew Wilson",
    age: 33,
    email: "matthew.wilson@example.com",
    address: "999 Pine Lane, Metrotown",
    phone: "555-567-8901",
  },
  {
    name: "Sofia Garcia",
    age: 27,
    email: "sofia.garcia@example.com",
    address: "111 Elm Avenue, Megatown",
    phone: "555-678-9012",
  },
  {
    name: "Jackson Hernandez",
    age: 25,
    email: "jackson.hernandez@example.com",
    address: "222 Cedar Road, Smallburg",
    phone: "555-789-0123",
  },
  {
    name: "Grace Rodriguez",
    age: 28,
    email: "grace.rodriguez@example.com",
    address: "333 Maple Court, Countytown",
    phone: "555-890-1234",
  },
  {
    name: "Henry King",
    age: 31,
    email: "henry.king@example.com",
    address: "444 Birch Street, Boroughville",
    phone: "555-901-2345",
  },
  {
    name: "Scarlett Anderson",
    age: 24,
    email: "scarlett.anderson@example.com",
    address: "555 Pine Road, Townland",
    phone: "555-012-3456",
  },
  {
    name: "Liam Martinez",
    age: 26,
    email: "liam.martinez@example.com",
    address: "666 Elm Avenue, Cityburg",
    phone: "555-123-4567",
  },
  {
    name: "Chloe Taylor",
    age: 33,
    email: "chloe.taylor@example.com",
    address: "777 Cedar Lane, Villaville",
    phone: "555-234-5678",
  },
  {
    name: "Emma Adams",
    age: 30,
    email: "emma.adams@example.com",
    address: "888 Maple Street, Hamletville",
    phone: "555-345-6789",
  },
  {
    name: "Oliver Jackson",
    age: 28,
    email: "oliver.jackson@example.com",
    address: "999 Elm Road, Suburbtown",
    phone: "555-456-7890",
  },
  {
    name: "Ava Garcia",
    age: 27,
    email: "ava.garcia@example.com",
    address: "111 Pine Avenue, Urbantown",
    phone: "555-567-8901",
  },
];
